name: CI
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Konfiguracja PNPM (kluczowe!)
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      # To pozwala Nx-owi wiedzieć, co się zmieniło
      - name: Derive appropriate SHAs for help with affected commands
        uses: nrwl/nx-set-shas@v4

      - name: Lint
        run: pnpm nx affected --target=lint --parallel=3

      - name: Build
        run: pnpm nx affected --target=build --parallel=3